### ISSUE TITLE
please add cloudfront_access_identity_arn to outputs

### ISSUE THREAD

**Issue by hakamadare** [FitnessKeeper/terraform-aws-s3-cloudfront#7]
for the scenario where the bucket is created outside our module, someone else will have to modify the bucket policy to allow our cloudfront_access_identity to read objects from the bucket, and outputting the ARN of the identity will make that easier.

**Comment by hakamadare** [comment]
specifically output the `iam_arn` attribute, see https://www.terraform.io/docs/providers/aws/r/cloudfront_origin_access_identity.html

**Comment by jnoss** [comment]
Done via PR #6
